### ISSUE TITLE
When you archive the SDKs, you should preserve the permission of the files

### ISSUE THREAD

**Issue by Jeswang** [phracker/MacOSX-SDKs#1]
The links in the framework became unreachable after I unarchive your online disk files.

If your using a command to archive those SDKs, you should add -p in the command line:

![image](https://cloud.githubusercontent.com/assets/553783/4076743/02275618-2ebd-11e4-9d03-9b1afb4b4d65.png)

Useful link: http://www.linuxquestions.org/questions/linux-newbie-8/tar-preserve-the-symbolic-links-927221/

**Comment by phracker** [comment]
Duly noted.
