### ISSUE TITLE
10.11 SDK Missing DMG file

### ISSUE THREAD

**Issue by vinnytammu** [phracker/MacOSX-SDKs#19]
I need the old 10.11 xcode for my openframeworks project to work. Upon extracting the zip file, I found no DMG file. 

I need this DMG file in order to proceed with my project. https://forum.openframeworks.cc/t/quicktime-quicktime-h-file-not-found/24494/3

<img width="766" alt="Screen Shot 2019-04-15 at 16 39 10" src="https://user-images.githubusercontent.com/11380568/56145960-44c86a00-5f9d-11e9-987e-50f68e878cfc.png">

**Comment by Archetrix** [comment]
@vinnytammu with your Apple Developer account you can log into https://developer.apple.com/download/more/ and search for "Xcode 7" which was the earliest version supporting 10.11.
The SDK files @phracker is providing here is for those who want to use latest Xcode for compiling apps compatible with older macOS versions. Xcode usually ships with latest SDKs only.

**Comment by phracker** [comment]
@vinnytammu this project does not provide dmg files used for installation, just the .sdk folders provided by each version of Xcode.
