### ISSUE TITLE
Tarball release for 10.14 missing

### ISSUE THREAD

**Issue by rossburton** [phracker/MacOSX-SDKs#22]
Please add a tarball release for the 10.14 SDK.

**Comment by katzer** [comment]
@phracker and for 10.15 as well please

**Comment by marcoscaceres** [comment]
🎄kind xmas bump 🎄

**Comment by bkotsopoulossc** [comment]
Bump

**Comment by bkotzz** [comment]
I forked the repo and made a release, https://github.com/bkotzz/MacOSX-SDKs/releases/download/macos_1014/MacOSX10.14.sdk.tar.gz

**Comment by phracker** [comment]
Fixed. Check the releaaes tab.
