### ISSUE TITLE
Is it legal to distribute these SDKs

### ISSUE THREAD

**Issue by mattatobin** [phracker/MacOSX-SDKs#26]
I am concerned about the legality of distributing these SDKs because you are not Apple or the reliability of existence of this repo in the long term.

**Comment by mattatobin** [comment]
Let me clarity, I want to be able to rely on this repo's perpetual existance as it is a good resource but my consern is Apple could DMCA it in a second.

**Comment by CodeAsm** [comment]
been 4 years now. Apple would know by now? its 1 phonecall to MS
