### ISSUE TITLE
MinimumSDKVersion

### ISSUE THREAD

**Issue by abhibeckert** [phracker/MacOSX-SDKs#9]
It's now necessary to edit `MinimumSDKVersion` in the platform info plist:

    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

Perhaps some instructions for doing this could be in the readme?

**Comment by galambalazs** [comment]
+1 this was driving me mad

**Comment by phracker** [comment]
Merged @galambalazs's patch. Thanks for notifying me!
